hand_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - joint_51
     - joint_52

  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      joint_51: {trajectory: 0.1, goal: 0.1}
      joint_52: {trajectory: 0.1, goal: 0.1}


  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
joint_group_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
     - joint_51
     - joint_52
